import os.path

DATA_DIR = 'data'
WAV_DIR = os.path.join(DATA_DIR, "NIPS4B_BIRD_CHALLENGE_TRAIN_TEST_WAV")
MFCC_DIR = os.path.join(DATA_DIR, "NIPS4B_BIRD_CHALLENGE_TRAIN_TEST_MFCC")
LABEL_DIR = os.path.join(DATA_DIR, "NIPS4B_BIRD_CHALLENGE_TRAIN_LABELS")
